### ISSUE TITLE
[Question] What font is used in the screenshots?

### ISSUE THREAD

**Issue by lampewebdev** [Mehdi-Hp/Short-Giraffe#1]
Hey,  
first of all great work!  
I really like the font in the screenshots.  
Could you please tell me which one it is?

**Comment by kumamaki** [comment]
Hey,
Thanks. It's `RecursiveMono`. You can find it here:  
https://www.recursive.design/

**Comment by lampewebdev** [comment]
@Mehdi-Hp thank you very much!  

Really nice theme!
It is now my daily driver :)
